@startuml

participant "Issuer" as IS
participant "Bedrock Documentation" as DOCS
participant "Bedrock Trustee/Steward" as TR
participant "Ledger" as LE

group Onboard Issuer as Endorser
IS->DOCS: Potential issuer searches for options on how to be an issuer
DOCS->IS: Options found, Trustee/Steward/Endorser contact information supplied
IS->TR: Express interest in becoming endorser on Bedrock
TR->IS: Request for information, including Bedrock Endorser Agreement
IS->IS: Create seed, DID, key pair in agent
IS->TR: Information (incl. DID, public key) provided, agreement signed
TR->TR: Keeps endorser application, information for audit purposes
TR->LE: Writes DID, public key with endorser role
LE->TR: Write confirmed
TR->TR: Use Indyscan to confirm DID on Ledger
TR->IS: Notified of success
IS->LE: Using agent, credential schema transaction signed with endorser private key, written to ledger
end

@enduml
